### ISSUE TITLE
let broken

### ISSUE THREAD

**Issue by lukescott** [6to5/6to5#605]
```javascript
{
  let one;
  let two;
  two;
}
```

Transpiles to:

```javascript
{
  var one = undefined;
  var _two = undefined;
  two;
}
```

**Comment by sebmck** [comment]
Fixed in 3.0.4

**Comment by lukescott** [comment]
@sebmck I'm running 3.0.5.

**Comment by sebmck** [comment]
@lukescott Are you sure? I can't replicate this locally or on the [REPL](http://6to5.org/repl/#?experimental=true&playground=true&evaluate=true&loose=false&=&code=%7B%0A%20%20let%20one%3B%0A%20%20let%20two%3B%0A%20%20two%3B%0A%7D). Does running `$ 6to5 -V` output 3.0.5?

**Comment by lukescott** [comment]
@sebmck The simple test case works, but I'm still having an issue. Here's actual code:

```javascript
	function load(object = {}) {
		for (let key in object) {
			if (object.hasOwnProperty(key)) {
				let value = object[key];
				let child = this.find(key)[0];
				if (!child) {
					continue;
				}
				if (hasTrait(child, Input)) {
					child.load(value);
				}
			}
		}
	}
```

The `child` var is named `_child`.

**Comment by sebmck** [comment]
@lukescott Ah. I'll look into it now.

**Comment by sebmck** [comment]
@lukescott Tracked it down. I'll push out a new patch shortly.

**Comment by sebmck** [comment]
@lukescott Fixed as of 3.0.6. Sorry about that!

**Comment by lukescott** [comment]
@sebmck That did it, thanks! All my tests are passing now :+1:
